version: "3.9"
services: 
    backend:
        build: ./fastify-back-end
        ports: 
            - "127.0.0.1:4000:4000"
        env_file:
            - "./fastify-back-end/.env"
        command: npm run dev
        volumes: 
            - "./fastify-back-end/node_modules/:/home/zulfikra/node_modules"
            - "./fastify-back-end:/home/zulfikra"
    front_end:
        build: ./front-end
        ports:
            - "3000:3000"
            - "8002:8002"
        volumes:
            - "./front-end:/home/front-end" 
            - "./front-end/.env:/home/front-end/.env"
        command: sh -c " npm run dev"
        env_file:
            - "./front-end/.env"
    redis:
        image: redis
        hostname: "redis"
        ports: 
            - "6666:6666"
        expose: 
            - "6666"
        command: --port 6666
    database:
        image: postgres:13-alpine
        env_file: 
            - "./fastify-back-end/.env"
        command: "-p 5678"
        ports: 
            - "5678:5678"
        expose: 
            - "5678"
        volumes: 
            - "./postgres:/var/lib/postgresql/data"
volumes: 
    controllers: {}
    
